### ISSUE TITLE
NextJS page based resource.name

### ISSUE THREAD

**Issue by Meemaw** [DataDog/dd-trace-js#1750]
It would be great if `NextJS` did per page based `resource.name` tagging (or allow customising of it).

We currently have to hack this by overriding it ourselves doing something like this in our middleware:
```js
const root = req._datadog.span
// Set resource name to path pattern
root.setTag("resource.name", route.pattern)
```

This allows us to get a very powerful grouping per resource/page that would look something like this:

<img width="1507" alt="Screenshot 2022-01-12 at 12 02 38" src="https://user-images.githubusercontent.com/8524109/149128429-10fbf216-c650-4486-9ea2-788981db795d.png">

**Comment by rochdev** [comment]
This should already be the case. Are you looking at `http.request` or `next.request` on the service page? If `next.request` is selected you should see the routes for Next specifically as they don't bubble up to the root span. You can also set it as the primary operation if you're mostly interested in Next metadata.

**Comment by Meemaw** [comment]
<img width="958" alt="Screenshot 2022-01-14 at 16 41 38" src="https://user-images.githubusercontent.com/8524109/149543026-97b04a6f-0ccb-40b2-8fa6-ecc84aac452b.png">

Seems the `resource.name` for `next.request` is just `GET`, which kinda correlated to this code: https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-next/src/index.js#L101

**Comment by rochdev** [comment]
This is just the default, and the resource name is later updated according to the page. It's possible it's not working for you case as NextJS has a complex router internally, so it's possible there are cases not handled properly. Can you provide a reproduction snippet that I could try?

**Comment by rochdev** [comment]
@Meemaw Are you still having this issue?

**Comment by Meemaw** [comment]
Yes

**Comment by rochdev** [comment]
One thing I'm wondering is if the tracer is initialized early enough, as load order issues can cause some of the metadata to be missing. Generally speaking the fact that the span is named `next.request` should indicate that it's loaded early enough, but for Next specifically it can be complicated to load first since there is no way to do that in code, so maybe something to look into. The only way for NextJS to load the tracer before all other imports is to use `NODE_OPTIONS='-r dd-trace/init'`. If this is already how you are initializing the tracer then there is definitely a bug and we would need a reproduction. If the tracer is initialized programmatically then I would try switching to this approach instead which should fix the issue.

**Comment by Eronarn** [comment]
I'm also having this issue. All of our traces just come in as `GET` or `POST` as the resource name, even though they do have path information in the `http` section of the trace data.

I did try to use `-r` preloading to load the DD libraries, which didn't fix this either.

Can't share the codebase but if there's something diagnostic you have I'm willing to run it

**Comment by Klemensas** [comment]
> I'm also having this issue. All of our traces just come in as `GET` or `POST` as the resource name, even though they do have path information in the `http` section of the trace data.

The same thing started happening to us. This started after we upgraded to next 12 and the latest `dd-trace`, not sure which of these could be the cause.
We use preloading.

**Comment by meyer9** [comment]
Looks like the function signature for `findPageComponents` changed recently: https://github.com/vercel/next.js/commit/5f95b6b05031201b04d89cee7b6161296bbe7058#diff-2b8e3503c1bebf856610a5551d9c5996435b99f45db389d4eeac1b671518875eL240-R248

So this probably needs updating: https://github.com/vercel/next.js/commit/5f95b6b05031201b04d89cee7b6161296bbe7058#diff-2b8e3503c1bebf856610a5551d9c5996435b99f45db389d4eeac1b671518875eL240-R248

**Comment by walt1992** [comment]
So, Any solution? 

Have it resolved since then?

I still can't check the resource name.

**Comment by mrpatrickpilch** [comment]
Also experiencing this on Next.js 13

**Comment by WarpRat** [comment]
We see the same thing, the only operation available is `web.request` and the resource is just the same as the method with no additional information.

Package versions:
* next 13.2.4
* dd-trace 3.17.1

Environment:
* container built using the [example dockerfile](https://github.com/vercel/next.js/tree/canary/examples/with-docker)
* k8s deployment
* container started with CMD `node server.js`
* ALB > nginx-ingress > k8s service

I ran into issues with the standalone build not including the `dd-trace` package so I ended up doing an additional `npm install dd-trace` in the final layer of the Dockerfile (which makes it not really a standalone build anymore 🤷). We use the `NODE_OPTIONS='-r dd-trace/init'` method to require the package at start up. Using this method we also ran into the issue described in [this github issue](https://github.com/vercel/next.js/issues/40735) which required editing the nextjs `package.json` to change the main entrypoint to something dd-trace would find.

Most of my experience with dd-trace has been in python services and getting it running with next has been far more difficult than I anticipated. I'm not sure if some of the workarounds I've need to use to get it to run at all are impacting the infromation included in the traces. There may potentially be away to do this better using either nextjs' instrumentation feature or somehow hooking into the Vercel provided otel hooks but I wasn't quite able to get either option to work.

@Meemaw - are you just adding that to a `middleware.js` in the root of your next project according to the [docs](https://nextjs.org/docs/advanced-features/middleware)?

**Comment by david-alpert-nl** [comment]
I am seeing something related.

I am seeing a `next.request` span that has the url or path_group added but that `next.request` is not the root span.

instead the root span seems to be `web.request` which is simply `GET`, which means that in Datadog we cannot easily filter those root spans; all requests seem to be collected under a single resource.

![image](https://user-images.githubusercontent.com/112503249/233201861-e6ba52ac-0e91-40a6-a9ac-3730da1713fc.png)

node version:
```
16.17.0
```

nextjs version:
```
    "next": "12.3.1",
```
    
dd-trace version:
```
 "dd-trace": "^3.13.2",
```

**Comment by david-alpert-nl** [comment]
it looks like the top level `web.request` span is not getting the `http.path_group` property added to it

**Comment by EmilioAiolfi** [comment]
Folks this PR https://github.com/DataDog/dd-trace-js/pull/2743
![Screenshot 2023-06-05 at 15 32 33](https://github.com/DataDog/dd-trace-js/assets/999120/012595a2-dfda-41da-89ab-bdface7ee941)

Created a problem with the page path, now show [Object, object] and it doesn't show the dependency map

next: "12.3.4",
dd-trace: "4.0.0"

**Comment by rochdev** [comment]
@EmilioAiolfi Can you provide a reproduction? Looking at the code I don't see how to reproduce this, and it doesn't happen in our tests either.

**Comment by vr** [comment]
Same issue here, what do you need to reproduce/fix ?

**Comment by rochdev** [comment]
@vr Just a small project or even code snippet that reproduces the incorrect resource name.

**Comment by VivaLaPanda** [comment]
This happens for me as well:


<img width="870" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/6300466/a72f63b0-f722-4fd2-a2eb-253ecb170980">

<img width="919" alt="image" src="https://github.com/DataDog/dd-trace-js/assets/6300466/1a683774-af47-4e92-b8e2-1273477bb966">

**Comment by zomgbre** [comment]
We are seeing the same issue on 4.11.0. 

It is not clear how to use the workaround mentioned in the original post. Anyone care to share the workaround in full context? Or could we have it fixed. Pretty please 🥺

**Comment by jalessio** [comment]
FYI to followers of this issue, the fix for this from PR https://github.com/DataDog/dd-trace-js/pull/3537 made it into [v4.12.0](https://github.com/DataDog/dd-trace-js/releases/tag/v4.12.0).

That said, I have upgraded to [v4.12.0](https://github.com/DataDog/dd-trace-js/releases/tag/v4.12.0) and I'm still only seeing `GET` as the resource name in APM so I'm not sure what else I'm missing (currently running NextJS `v13.4.12`).

**Comment by dpihlaja** [comment]
Still seeing this on 5.28.0, not sure if this was a regression if it was actually ever fixed on 4.12.0 however.
